/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/scene.gltf -o src/Ship.js -r public 
Author: (Andy An)norbyscook (https://sketchfab.com/norbyscook)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-maintenance-robot-a612ed4feea14fc390beeb3a47943054
Title: space maintenance robot
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Ship = (props) => {
  const { nodes, materials } = useGLTF("/models/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["defaultMat.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/models/scene.gltf");

export default Ship;
