/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Vanguard.gltf -o src/Vanguard.jsx -r public 
*/

import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { Canvas } from "@react-three/fiber";

export function Vanguard(props) {
  const { nodes, materials } = useGLTF("/models/Vanguard.gltf");
  return (
    <Canvas>
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.vanguard_visor.geometry}
          material={materials.Vanguard_VisorMat}
        />
        <mesh
          geometry={nodes.vanguard_Mesh.geometry}
          material={materials.VanguardBodyMat}
        />
      </group>
      <ambientLight intensity={0.5} />
      <OrbitControls />
    </Canvas>
  );
}

useGLTF.preload("/models/Vanguard.gltf");
export default Vanguard;
